### ISSUE TITLE
CARBMETER -Backend -GraphQL API exposition for Frontend

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/carbonmeter-rs#8]
Description
--------------------------
Retrieving information using GraphQL API for Frontend

Additional Context
---------------------------------
Excalidraw design:
https://app.excalidraw.com/s/4BTLOTSvKjp/3deoF6DDILD

Acceptance Criteria
----------------------------
- [ ] GraphQL API exposition for Frontend

**Comment by MartianGreed** [comment]
Done without graphql as rest query endpoints perfectly suits the needs
